SET PATH=C:\Keil\ARM\BIN40\;C:\Program Files\ARM\ADSv1_2\bin;C:\WinAVR-20100110\bin;C:\WinAVR-20100110\utils\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\MATLAB\R2010b\runtime\win32;C:\Program Files\MATLAB\R2010b\bin
SET ARMCC41INC=C:\Keil\ARM\RV31\INC
SET ARMCC41LIB=C:\Keil\ARM\RV31\LIB
SET CPU_TYPE=S3C2440A
SET CPU_VENDOR=Samsung
SET UV2_TARGET=Target 1
SET CPU_CLOCK=0x00000000
"C:\Keil\ARM\BIN40\ArmAsm" --Via "2440init._ia"
"C:\Keil\ARM\BIN40\ArmAsm" --Via "2440slib._ia"
"C:\Keil\ARM\BIN40\ArmCC" --Via "nand.__i"
"C:\Keil\ARM\BIN40\ArmCC" --Via "2440lib.__i"
"C:\Keil\ARM\BIN40\ArmCC" --Via "adc.__i"
"C:\Keil\ARM\BIN40\ArmCC" --Via "keyscan.__i"
"C:\Keil\ARM\BIN40\ArmCC" --Via "lcd_tft.__i"
"C:\Keil\ARM\BIN40\ArmCC" --Via "main.__i"
"C:\Keil\ARM\BIN40\ArmCC" --Via "memtest.__i"
"C:\Keil\ARM\BIN40\ArmCC" --Via "mmu.__i"
"C:\Keil\ARM\BIN40\ArmCC" --Via "pic.__i"
"C:\Keil\ARM\BIN40\ArmCC" --Via "profile.__i"
"C:\Keil\ARM\BIN40\ArmCC" --Via "rtc.__i"
"C:\Keil\ARM\BIN40\ArmCC" --Via "sd_mmc.__i"
"C:\Keil\ARM\BIN40\ArmCC" --Via "touchpanel.__i"
"C:\Keil\ARM\BIN40\ArmCC" --Via "tq_logo.__i"
